### ISSUE TITLE
Segmentation fault when reading saved files

### ISSUE THREAD

**Issue by dforsi** [Guenael/rtlsdr-ft8d#63]
When trying to read a file saved by rtlsdr_ft8d itself, the block of code that would print a "No spot" message fails as follows:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000040471d in printSpots (n_results=<optimized out>) at rtlsdr_ft8d.c:597
597                    rx_state.gtm->tm_year + 1900,
(gdb) bt
#0  0x000000000040471d in printSpots (n_results=<optimized out>) at rtlsdr_ft8d.c:597
#1  decodeRecordedFile (filename=<optimized out>) at rtlsdr_ft8d.c:773
#2  0x00000000004067fb in main (argc=9, argv=0x7fffffffde38) at rtlsdr_ft8d.c:1014
(gdb) p rx_state.gtm
$1 = (struct tm *) 0x0
```

**Comment by Guenael** [comment]
Fixed in this MR : https://github.com/Guenael/rtlsdr-ft8d/pull/65
Thanks @dforsi for this bug report!
